server:
  port: 8082

spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/reminder1?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: reminder
    password: reminder
